1. What does Pandas stand for?
> **Pandas comes from 'Panel Data' - It represents both 'Panel Data' and 'Python Data Analysis'**
2. What are the 2 collections used in Pandas?
> * **Series**
> * **DataFrame**
3. Name 4 things Pandas can do for us.
> * **Data Cleansing**
> * **Data Normalization**
> * **Statistical Analysis**
> * **Merges and Joins**
4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
> **inplace**
5. What is a CSV?
> **A CSV is a comma separated file - It is a simple way to store big data sets and contains plain text.**
6. When cleaning data, what values do we not like in our data?
> **Missing or Unknown**

In [5]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of ... 
# (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

arrayA = np.array([2, 3, 2])

# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

arrayB = np.linspace(0, 20, num=6)
print(arrayB)

# 9. Make a Deep Copy of the above array

import copy
arrayC = copy.deepcopy(arrayB)
print(arrayC)


[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [14]:
# 11. Concatenate these 3 arrays into a new array named 'newArray'...

arrayD = np.array([[25, 16]])
arrayE = np.array([[11, 2], [13, 4]])
arrayF = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayD, arrayE, arrayF), axis=0)
print(newArray)



[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [12]:
# 12. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [13]:
# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', 
# so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2,2,3)
print(reshapedArray)

[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]


In [21]:
# 14. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

unpack = ([[16, 25, 2],
  [11, 4, 13],

 [7, 81, 5],
  [6, 11, 12]])

[[a, b, c],
  [d, e, f],

 [g, h, i],
  [j, k, l]] = unpack

print(a, b, c)
print(d, e, f)
print(g, h, i)
print(j, k, l)


16 25 2
11 4 13
7 81 5
6 11 12


In [22]:
# 15. Combined and sort the following arrays into one called 'comboArray' ...
# Combined
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis=0)
print(comboArray)


[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]


In [23]:
# 15 - Sorted
print(np.sort(comboArray))

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [26]:
# 16. Take 'comboArray' and perform the following slicing activities:

sec1 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec1[0, 1])

1


In [27]:
sec2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec2[0, 2:])

[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [28]:
sec3 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec3[0, 3:13])

[ 3  4  5  6  7 10 11 12 13 14]


In [31]:
sec4 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec4[0, -6:])

[22 23 24 25 26 27]


In [34]:
sec5 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec5[0, -24:-10])

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]


In [35]:
sec6 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec6[0, -8:])

[20 21 22 23 24 25 26 27]


In [40]:
sec7 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]])
print(sec7[0, :-1: 5])

[ 0  5 12 17 24]


In [44]:
# 20. Using Series, create a DataFrame that looks like this:
import pandas as pd

# Create Series
ingredients = pd.Series(["Flour","Milk","Eggs","Spam"])
quantity = pd.Series([4,1,2,1])
unit = pd.Series(["cups", "cup", "large", "can"])

# Make into DataFrame
df = pd.concat([ingredients, quantity, unit], axis=1)

# Add Column Names
ingredients = pd.Series(["Flour","Milk","Eggs","Spam"], name='Ingredients')
quantity = pd.Series([4,1,2,1], name='Quantity')
unit = pd.Series(["cups", "cup", "large", "can"], name='Unit')
df = pd.concat([ingredients, quantity, unit], axis=1)
print(df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [45]:
# 21. Take this data and creat a DataFrame named studentData

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [47]:
# 22. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["Deserts"] = deserts
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [48]:
# 23. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
# Sort by Name

studentData.sort_values(by = ['Name'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [49]:
# 23 - Sort by address

studentData.sort_values(by = ['address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
2       waffels  
3  Carrot Halwa  
0     ice cream  
1  Cashew Fudge  


In [50]:
# 24. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')


In [52]:
# 25. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, 
# make a change to your CSV file, and save a copy with a different name.

veggies= pd.DataFrame({'Sweet Corn Sold': [100, 250, 700, 300], 'Beans Sold': [500, 450, 345, 680], 'Squash Sold': [789, 418, 765, 100]}, index=['Quarter 1', 'Quarter 2', 'Quarter 3', 'Quarter 4'])
veggies.to_csv('Vegetable_Quarterly_Sales.csv')

In [59]:
# Make a change to CSV

cucumbers = [150, 300, 450, 600]
veggiesextended = veggies.assign(Cucumbers_Sold=cucumbers)
veggiesextended.to_csv('Updated_Vegetable_Quarterly_Sales.csv')
